apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: fastapi
resources:
  - ../../bases/fastapi
patchesStrategicMerge:
  - overrides-fastapi.yaml
images:
  - name: registry.met.no/s-enda/container-fastapi
    newTag: latest
