name: base
channels:
- conda-forge
dependencies:
- python=3.11
- pip
- wheel
- Jinja2
- gunicorn
- pyyaml
- xarray=2024.6.0
- boto3
- netcdf4
- jinja2
- pytest-mock
- rasterio
- pandas
- satpy=0.49.0
- mapserver=8.0.2
- gdal=3.9.0
- cartopy
- metpy
- lxml
- cmocean
- pyspectral
