name: base
channels:
- conda-forge
dependencies:
- python=3.12
- pip
- wheel
- Jinja2
#- gunicorn
- pyyaml
- xarray # =2024.9.0 #=2024.6.0
- boto3
- netcdf4
- jinja2
- pytest-mock
- rasterio
- pandas
- satpy=0.60.0
- trollimage
- mapserver=8.6.0
- gdal  #3.9.0
- libgdal
- cartopy
- metpy
- lxml
- cmocean
- pyspectral
- curl
