---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: fastapi
configMapGenerator:
- name: fastapi-app-config
  files:
    - config/fastapi-config.yml
resources:
  - fastapi-deployment.yaml
