name: test-environment
channels:
  - conda-forge
dependencies:
  - jinja2
  - pyyaml
  - pytest-mock
  - uvicorn
  - requests
  - boto3
  - rasterio
  - satpy
  - mapserver=8.2.2
  - gdal=3.9.2
  - libgdal=3.9.2
  - cmocean
  - lxml
  - cartopy
  - metpy
  - pandas
  - pip
  - pip:
    - pytest-lazy-fixtures
    - pytest-timeout
    - pytest
    - pytest-cov
    - WebTest
 